services:
  assistant_app:
    build: .
    env_file:
      - .env
    # depends_on:
    #   - redis
    restart: unless-stopped
    ports:
      - "${PORT}:8000"
    volumes:
      - ./db.sqlite3:/code/db.sqlite3

  # redis:
  #   image: redis:8
  #   restart: unless-stopped
  #   ports:
  #     - "${REDIS_PORT}:6379"
  #   volumes:
  #     - redis_data:/data

# volumes section is not needed for bind-mounting a file in the main directory

