services:
  assistant_app:
    build: .
    env_file:
      - .env
    # depends_on:
    #   - redis
    restart: unless-stopped
    ports:
      - "${PORT}:8000"
    volumes:
      - data:/code/data

  # redis:
  #   image: redis:8
  #   restart: unless-stopped
  #   ports:
  #     - "${REDIS_PORT}:6379"
  #   volumes:
  #     - redis_data:/data

volumes:
  data:
